# .github/workflows/docker-image.yml
name: Build and Push Docker

on:
  push:
    branches: [ "main" ]           # run every time you push main
  workflow_dispatch:               # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write              # allow push to GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nea:1.1.0
